// Code generated by protoc-gen-go. DO NOT EDIT.
// source: meta.proto

package bitswap_meta_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MetaUnit struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaUnit) Reset()         { *m = MetaUnit{} }
func (m *MetaUnit) String() string { return proto.CompactTextString(m) }
func (*MetaUnit) ProtoMessage()    {}
func (*MetaUnit) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{0}
}

func (m *MetaUnit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaUnit.Unmarshal(m, b)
}
func (m *MetaUnit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaUnit.Marshal(b, m, deterministic)
}
func (m *MetaUnit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaUnit.Merge(m, src)
}
func (m *MetaUnit) XXX_Size() int {
	return xxx_messageInfo_MetaUnit.Size(m)
}
func (m *MetaUnit) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaUnit.DiscardUnknown(m)
}

var xxx_messageInfo_MetaUnit proto.InternalMessageInfo

func (m *MetaUnit) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MetaUnit) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Meta struct {
	Units                []*MetaUnit `protobuf:"bytes,1,rep,name=units,proto3" json:"units,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{1}
}

func (m *Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meta.Unmarshal(m, b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
}
func (m *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(m, src)
}
func (m *Meta) XXX_Size() int {
	return xxx_messageInfo_Meta.Size(m)
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

func (m *Meta) GetUnits() []*MetaUnit {
	if m != nil {
		return m.Units
	}
	return nil
}

func init() {
	proto.RegisterType((*MetaUnit)(nil), "bitswap.meta.pb.MetaUnit")
	proto.RegisterType((*Meta)(nil), "bitswap.meta.pb.Meta")
}

func init() { proto.RegisterFile("meta.proto", fileDescriptor_3b5ea8fe65782bcc) }

var fileDescriptor_3b5ea8fe65782bcc = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x4d, 0x2d, 0x49,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4f, 0xca, 0x2c, 0x29, 0x2e, 0x4f, 0x2c, 0xd0,
	0x83, 0x88, 0x25, 0x29, 0x19, 0x71, 0x71, 0xf8, 0xa6, 0x96, 0x24, 0x86, 0xe6, 0x65, 0x96, 0x08,
	0x09, 0x70, 0x31, 0x67, 0xa7, 0x56, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0x98, 0x42,
	0x22, 0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x10,
	0x8e, 0x92, 0x39, 0x17, 0x0b, 0x48, 0x8f, 0x90, 0x3e, 0x17, 0x6b, 0x69, 0x5e, 0x66, 0x49, 0xb1,
	0x04, 0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0xa4, 0x1e, 0x9a, 0xe1, 0x7a, 0x30, 0x93, 0x83, 0x20,
	0xea, 0x92, 0xd8, 0xc0, 0x8e, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x89, 0x72, 0xf0, 0x93,
	0x92, 0x00, 0x00, 0x00,
}
