// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package bitswap_message_pb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	pb "github.com/proximax-storage/go-bitswap/meta/pb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Wantlist             *Message_Wantlist `protobuf:"bytes,1,opt,name=wantlist,proto3" json:"wantlist,omitempty"`
	Payload              []*Message_Block  `protobuf:"bytes,2,rep,name=payload,proto3" json:"payload,omitempty"`
	Meta                 *pb.Meta          `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetWantlist() *Message_Wantlist {
	if m != nil {
		return m.Wantlist
	}
	return nil
}

func (m *Message) GetPayload() []*Message_Block {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetMeta() *pb.Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type Message_Wantlist struct {
	Entries              []*Message_Wantlist_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Message_Wantlist) Reset()         { *m = Message_Wantlist{} }
func (m *Message_Wantlist) String() string { return proto.CompactTextString(m) }
func (*Message_Wantlist) ProtoMessage()    {}
func (*Message_Wantlist) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 0}
}

func (m *Message_Wantlist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_Wantlist.Unmarshal(m, b)
}
func (m *Message_Wantlist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_Wantlist.Marshal(b, m, deterministic)
}
func (m *Message_Wantlist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_Wantlist.Merge(m, src)
}
func (m *Message_Wantlist) XXX_Size() int {
	return xxx_messageInfo_Message_Wantlist.Size(m)
}
func (m *Message_Wantlist) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_Wantlist.DiscardUnknown(m)
}

var xxx_messageInfo_Message_Wantlist proto.InternalMessageInfo

func (m *Message_Wantlist) GetEntries() []*Message_Wantlist_Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type Message_Wantlist_Entry struct {
	Cid                  []byte   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message_Wantlist_Entry) Reset()         { *m = Message_Wantlist_Entry{} }
func (m *Message_Wantlist_Entry) String() string { return proto.CompactTextString(m) }
func (*Message_Wantlist_Entry) ProtoMessage()    {}
func (*Message_Wantlist_Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 0, 0}
}

func (m *Message_Wantlist_Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_Wantlist_Entry.Unmarshal(m, b)
}
func (m *Message_Wantlist_Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_Wantlist_Entry.Marshal(b, m, deterministic)
}
func (m *Message_Wantlist_Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_Wantlist_Entry.Merge(m, src)
}
func (m *Message_Wantlist_Entry) XXX_Size() int {
	return xxx_messageInfo_Message_Wantlist_Entry.Size(m)
}
func (m *Message_Wantlist_Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_Wantlist_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Message_Wantlist_Entry proto.InternalMessageInfo

func (m *Message_Wantlist_Entry) GetCid() []byte {
	if m != nil {
		return m.Cid
	}
	return nil
}

type Message_Block struct {
	Prefix               []byte   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message_Block) Reset()         { *m = Message_Block{} }
func (m *Message_Block) String() string { return proto.CompactTextString(m) }
func (*Message_Block) ProtoMessage()    {}
func (*Message_Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 1}
}

func (m *Message_Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_Block.Unmarshal(m, b)
}
func (m *Message_Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_Block.Marshal(b, m, deterministic)
}
func (m *Message_Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_Block.Merge(m, src)
}
func (m *Message_Block) XXX_Size() int {
	return xxx_messageInfo_Message_Block.Size(m)
}
func (m *Message_Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Message_Block proto.InternalMessageInfo

func (m *Message_Block) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *Message_Block) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "bitswap.message.pb.Message")
	proto.RegisterType((*Message_Wantlist)(nil), "bitswap.message.pb.Message.Wantlist")
	proto.RegisterType((*Message_Wantlist_Entry)(nil), "bitswap.message.pb.Message.Wantlist.Entry")
	proto.RegisterType((*Message_Block)(nil), "bitswap.message.pb.Message.Block")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0xed, 0xff, 0x32, 0x55, 0x90, 0x80, 0xb2, 0xee, 0xc5, 0x2a, 0x1e, 0xaa, 0xd0, 0x2c,
	0xb4, 0x27, 0x8f, 0x16, 0xf4, 0x20, 0x78, 0xe9, 0xc5, 0x73, 0xd2, 0x4d, 0x63, 0x70, 0x77, 0x13,
	0x93, 0x94, 0x6e, 0xdf, 0xd0, 0xa7, 0xf0, 0xea, 0x6b, 0xc8, 0xce, 0x66, 0x4b, 0x41, 0x10, 0x4f,
	0x3b, 0x33, 0xfb, 0x7d, 0xdf, 0xfc, 0x32, 0x70, 0x92, 0x0b, 0xe7, 0x98, 0x14, 0xd4, 0x58, 0xed,
	0x35, 0x21, 0x5c, 0x79, 0xb7, 0x65, 0x86, 0xee, 0xc7, 0x3c, 0x9e, 0x4a, 0xe5, 0xdf, 0x36, 0x9c,
	0xae, 0x74, 0x9e, 0x48, 0x2d, 0x75, 0x82, 0x52, 0xbe, 0x59, 0x63, 0x87, 0x0d, 0x56, 0x75, 0x44,
	0x7c, 0x7f, 0x20, 0x37, 0x56, 0x97, 0x2a, 0x67, 0xe5, 0xd4, 0x79, 0x6d, 0x99, 0x14, 0x89, 0xd4,
	0xd3, 0xb0, 0x21, 0xc9, 0x85, 0x67, 0x89, 0xe1, 0xf8, 0xad, 0xad, 0xd7, 0xdf, 0x6d, 0x18, 0xbc,
	0xd4, 0x8b, 0xc9, 0x13, 0x0c, 0xb7, 0xac, 0xf0, 0x99, 0x72, 0x3e, 0x6a, 0x8d, 0x5b, 0x93, 0xd1,
	0xec, 0x86, 0xfe, 0x86, 0xa3, 0x41, 0x4e, 0x5f, 0x83, 0x76, 0xd1, 0xfd, 0xfc, 0xba, 0x3c, 0x5a,
	0xee, 0xbd, 0xe4, 0x01, 0x06, 0x86, 0xed, 0x32, 0xcd, 0xd2, 0xa8, 0x3d, 0xee, 0x4c, 0x46, 0xb3,
	0xab, 0xbf, 0x62, 0x16, 0x99, 0x5e, 0xbd, 0x87, 0x8c, 0xc6, 0x47, 0x6e, 0xa1, 0x5b, 0x41, 0x46,
	0x1d, 0xc4, 0x38, 0x3b, 0xf0, 0x57, 0xe4, 0x95, 0xd9, 0xb3, 0x25, 0x4a, 0xe2, 0x0f, 0x18, 0x36,
	0x24, 0xe4, 0x19, 0x06, 0xa2, 0xf0, 0x56, 0x09, 0x17, 0xb5, 0x70, 0xf3, 0xdd, 0x7f, 0x1e, 0x40,
	0x1f, 0x0b, 0x6f, 0x77, 0x0d, 0x42, 0x08, 0x88, 0x2f, 0xa0, 0x87, 0x73, 0x72, 0x0a, 0x9d, 0x95,
	0x4a, 0xf1, 0x22, 0xc7, 0xcb, 0xaa, 0x8c, 0xe7, 0xd0, 0x43, 0x6a, 0x72, 0x0e, 0x7d, 0x63, 0xc5,
	0x5a, 0x95, 0xe1, 0x6f, 0xe8, 0x08, 0x81, 0x6e, 0xca, 0x3c, 0x8b, 0xda, 0x38, 0xc5, 0x9a, 0xf7,
	0xf1, 0xe0, 0xf3, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x85, 0x8a, 0x2c, 0xf8, 0xff, 0x01, 0x00,
	0x00,
}
